
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple AWS Lambda for creating users
Resources:
  GetSetsFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/POSTUser_Lambda-1.0-SNAPSHOT.jar
      Handler: com.revature.post_user.PostUserHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
#        - arn:aws:iam::904493219403:policy/dynamodb-write-ama